In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
np.random.seed(42)

def generate_data():
    length = np.random.normal(0.523992, 0.120093, 100)
    height = np.random.normal(0.139516, 0.041827, 100)
    diameter = np.random.normal(0.139516, 0.041827, 100)
    whole_w = np.random.normal(0.828742, 0.490389, 100)
    shucked_w = np.random.normal(0.359367, 0.221963, 100)
    viscera_W = np.random.normal(0.180594, 0.109614, 100)
    shell_w = np.random.normal(0.238831, 0.139203, 100)
    
    y = 0.5 * shell_w + 0.3 * whole_w + 0.2 * diameter
        
    df = pd.DataFrame({'length' : length, 'height': height, 'diameter': diameter, 'whole_weight': whole_w, 'shucked_weight': shucked_w, 'viscera_weight': viscera_W, 'shell_weight': shell_w, 'target': y})
    
    return df
    
df = generate_data()
df.head()

,length,height,diameter,whole_weight,shucked_weight,viscera_weight,shell_weight,target
0,0.583644,0.080315,0.154481,0.422212,0.005463,0.282116,0.344206,0.329663
1,0.507387,0.121922,0.162972,0.554035,0.226328,0.389893,0.110463,0.254036
2,0.601775,0.125181,0.184817,1.195207,0.360531,0.027291,0.359883,0.575467
3,0.706897,0.105959,0.183593,1.128061,0.369795,0.242303,0.427540,0.588907
4,0.495872,0.132770,0.081892,0.818492,0.259469,0.109274,0.296382,0.410117

In [ ]:
input_var = ['shell_weight', 'whole_weight', 'diameter'] 

X = df[input_var]
y = df['target']

    shell_weight  whole_weight  diameter
0       0.344206      0.422212  0.154481
1       0.110463      0.554035  0.162972
2       0.359883      1.195207  0.184817
3       0.427540      1.128061  0.183593
4       0.296382      0.818492  0.081892
..           ...           ...       ...
95      0.195741      0.598663  0.110534
96      0.284230     -0.011360  0.177144
97      0.064672      1.492666  0.152369
98      0.367458      0.772573  0.173516
99      0.213092      1.435754  0.165851

[100 rows x 3 columns]

In [7]:
w = np.zeros(3)
b = 0.0

def predict(X, w, b):
    y_cap = X.dot(w) + b
    return y_cap

def mean_sq_err(y, y_cap):
    loss = np.mean((y_cap - y)**2)
    return loss

def compute_gradients(X, y, y_pred):
    n = len(y)
    
    dw = (2/n) * X.T.dot(y_pred-y)
    db = (2/n) * (y_pred-y).sum()
    
    return dw, db

def update_param(w, b, dw, db, lr):
    w = w - lr*dw
    b = b - lr*db

    return w, b

In [8]:
lr = 0.0001
epochs = 1000

for e in range(epochs):
    y_cap = predict(X, w, b)
    loss = mean_sq_err(y, y_cap)
    dw, db = compute_gradients(X, y, y_cap)
    w, b = update_param(w, b, dw, db, lr)
    
    if e % 100 == 0:
        print(f'Epoch {e}, Loss: {loss}')

Epoch 0, Loss: 0.1942111530953259
Epoch 100, Loss: 0.1801532398012263
Epoch 200, Loss: 0.16714398675256364
Epoch 300, Loss: 0.15510512102476479
Epoch 400, Loss: 0.14396421218024394
Epoch 500, Loss: 0.13365423617008462
Epoch 600, Loss: 0.12411317178722676
Epoch 700, Loss: 0.11528362724143275
Epoch 800, Loss: 0.1071124946076644
Epoch 900, Loss: 0.099550630067326

In [12]:
new_sample = np.array([0.2, 0.6, 0.4])
predicted_age = new_sample.dot(w) + b
print(predicted_age)

0.11807410028646528